name: CI/CD via Makefile

# 📌 CI pour PR & push sur main, CD pour tags
# ✅ PR vers main       → lint + format + test (no Docker)
# ✅ Push sur main      → build, test, push "latest"
# ✅ Push d’un tag v*   → build, test, push avec tag versionné

on:
  push:
    branches: [main]
    tags: ['v*']
  pull_request:
    branches: [main]

env:
  PORT: 8000

jobs:
  build-test-push:
    runs-on: ubuntu-latest

    steps:
    ##########################################################################
    # 1️⃣ SETUP
    ##########################################################################

    - name: 🧾 Checkout code
      uses: actions/checkout@v3

    - name: 🔧 Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: 🔍 Ensure .python-version exists
      run: test -f .python-version

    - name: 🐍 Read Python version from file
      id: python_version
      run: echo "version=$(cat .python-version)" >> $GITHUB_OUTPUT

    - name: 🐍 Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: ${{ steps.python_version.outputs.version }}

    - name: 📦 Install Python dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    ##########################################################################
    # 2️⃣ ALWAYS: Code Quality & Testing
    ##########################################################################

    - name: ✅ Run make check (format + lint + test)
      run: make check

    ##########################################################################
    # 3️⃣ ONLY ON PUSH (main or tag): Build & Push Docker
    ##########################################################################

    - name: 🔐 Log in to Docker Hub
      if: github.event_name == 'push'
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: 🧪 Build, Run, Test, and Stop Docker container
      if: github.event_name == 'push'
      run: make deploy PORT=${PORT}

    ##########################################################################
    # 4️⃣ ON TAG PUSH (e.g., v1.2.3): Push Docker image with version tag
    ##########################################################################

    - name: 🚀 Push Docker image with version tag
      if: startsWith(github.ref, 'refs/tags/')
      run: |
        VERSION=${GITHUB_REF#refs/tags/}
        make push DOCKER_USERNAME=${{ secrets.DOCKER_USERNAME }} GIT_SHA=$VERSION

    ##########################################################################
    # 5️⃣ ON MAIN BRANCH PUSH: Push Docker image with "latest"
    ##########################################################################

    - name: 🐳 Push Docker image with "latest" tag
      if: github.ref == 'refs/heads/main'
      run: |
        make push DOCKER_USERNAME=${{ secrets.DOCKER_USERNAME }} GIT_SHA=latest
