# .github/workflows/ci-pr.yml
name: 🧪 CI - Pull Request

on:
  pull_request:
    branches: [main]

env:
  PORT: 8000

jobs:
  test-lint:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Ensure .python-version exists
        run: test -f .python-version

      - name: Read Python version
        id: python_version
        run: echo "version=$(cat .python-version)" >> $GITHUB_OUTPUT

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: ${{ steps.python_version.outputs.version }}

      - name: Install Python dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run make check (format + lint)
        run: make check
