name: CI/CD via Makefile

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

env:
  PORT: 8000

jobs:
  build-test-push:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Check .python-version exists
      run: test -f .python-version

    - name: Read Python version from .python-version
      id: python_version
      run: echo "version=$(cat .python-version)" >> $GITHUB_OUTPUT

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: ${{ steps.python_version.outputs.version }}

    - name: Install Python dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Run make check (format + lint + test)
      run: make check

    - name: Log in to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Build, Run, Test, and Stop Docker container
      run: make deploy PORT=${PORT}

    - name: Push Docker image to Docker Hub
      run: make push DOCKER_USERNAME=${{ secrets.DOCKER_USERNAME }}
